name: Ziptrrip CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      ####################################################
      # Frontend
      ####################################################

      - name: Install Frontend Dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: ./Frontend
        run: npm run lint

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

      ####################################################
      # Backend
      ####################################################

      - name: Install Backend Dependencies
        working-directory: ./Backend
        run: npm ci

      - name: Lint Backend
        working-directory: ./Backend
        run: npm run lint --if-present

      ####################################################
      # Docker
      ####################################################

      - name: Build Frontend Docker Image
        run: |
          docker build -t ziptrrip-frontend ./Frontend

      - name: Build Backend Docker Image
        run: |
          docker build -t ziptrrip-backend ./Backend
